### ISSUE TITLE
How to order collection by find method?

### ISSUE THREAD

**Issue by serdem** [amigrave/ringo-mongodb#2]
Hi, there is orderBy parameter in findOne method but not in find method.
I think it is misplaced. Why do I use orderBy parameter if I select one document only?

**Comment by amigrave** [comment]
Well actually AFAIK that's how the java api works. ringo-mongodb is just a wrapper around it:

`findOne()`
https://github.com/mongodb/mongo-java-driver/blob/c173ed02bd4d8f625f4fcf0d01fe7c8eb2e41c74/src/main/com/mongodb/DBCollection.java#L884

`find()`
https://github.com/mongodb/mongo-java-driver/blob/c173ed02bd4d8f625f4fcf0d01fe7c8eb2e41c74/src/main/com/mongodb/DBCollection.java#L376

_java api:_
https://api.mongodb.org/java/2.13/com/mongodb/DBCollection.html#find(com.mongodb.DBObject,%20com.mongodb.DBObject)

I haven't looked at the beta driver tough. If the next java driver solves this issue, please re-open the issue.

Thanks.
